const TELAS = {

    TELA_INICIAL: 'TELA_INICIAL',

    TELA_CONSUMO_VEICULO: 'TELA_CONSUMO_VEICULO',

    TELA_CONVERSOR_MEDIDAS: 'TELA_CONVERSOR_MEDIDAS',

    TELA_CONVERSOR_MOEDA: 'TELA_CONVERSOR_MOEDA',

    TELA_MEDIA_NOTAS: 'TELA_MEDIA_NOTAS',

    TELA_CALCULADORA: 'TELA_CALCULADORA',

    TELA_REAJUSTE_SALARIAL: 'TELA_REAJUSTE_SALARIAL',

    TELA_CALCULO_IMC: 'TELA_CALCULO_IMC',

};

export default TELAS;